# Arquivo de configuração do Foot (~/.config/foot/foot.ini)
# Estética Cinza e Moderna (Importado do Alacritty)

font=monospace:size=14
pad=20x20 center

[cursor]
style=beam
blink=yes
color=181818 aaaaaa

[mouse]
hide-when-typing=yes

[colors]
background=181818
foreground=eeeeee

selection-foreground=181818
selection-background=888888

# normal colors
regular0=181818  # black (igual ao background)
regular1=dd5555  # red
regular2=d0d0d0  # green
regular3=c0c0c0  # yellow
regular4=b0b0b0  # blue
regular5=a0a0a0  # magenta
regular6=909090  # cyan
regular7=e0e0e0  # white

# bright colors
bright0=666666   # bright black
bright1=ff7777   # bright red
bright2=ffffff   # bright green
bright3=f0f0f0   # bright yellow
bright4=e8e8e8   # bright blue
bright5=d8d8d8   # bright magenta
bright6=c8c8c8   # bright cyan
bright7=ffffff   # bright white
